
services:
  postgres:
    image: postgres:17
    container_name: OnlineShopping.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: OnlineShopping
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
